name: Filter human changes to server

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  paths:
    if: ${{ !contains(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: json
          filters: |
            changed:
              - added|deleted: 'a/**'
      - name: Check if files were added or deleted by a human
        if: steps.filter.outputs.changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const commits = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const changedFiles = JSON.parse('${{ steps.filter.outputs.changed_files }}');
            commits.data.forEach(async commit => {
              const commitDetails = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: commit.sha,
              });
              commitDetails.data.files.forEach(file => {
                const author = commitDetails.data.author.login;
                if (file.status != "modified" &&
                  !author.includes("bot") &&
                  changedFiles.includes(file.filename)) {
                  core.setFailed(`${author} illegally ${file.status} ${file.filename}`);
                }
              });
            });
