---
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs: 
      manifest: ${{ toJSON(steps.rp.outputs) }}
    steps:
      - id: rp
        uses: GoogleCloudPlatform/release-please-action@v3.3.0
        with:
          command: manifest
  test:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: ${{ fromJSON(needs.release-please.outputs.manifest).releases_created }}
    strategy:
      matrix:
        path: ${{ fromJSON(fromJSON(needs.release-please.outputs.manifest).paths_released) }}
    steps:
       - uses: ./.github/workflows/test-template.yml
         with:
           path: ${{ matrix.path }}
