---
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs: 
      manifest: ${{ toJSON(steps.rp.outputs) }}
    steps:
      - id: rp
        uses: GoogleCloudPlatform/release-please-action@v3.3.0
        with:
          command: manifest
  test:
    env:
      manifest: ${{ fromJSON(needs.release-please.outputs.manifest) }}
    if: ${{ fromJSON(needs.release-please.outputs.manifest).releases_created }}
    needs: [release-please]
    strategy:
      matrix:
        path: ${{ fromJSON(env.manifest.paths_released) }}
    uses: ./.github/workflows/test-template.yml
    with:
      foo: ${{ matrix.path }}
      bar: ${{ env.manifest[format('{0}--tag_name', matrix.path] }}
