---
name: Test Cache

on:
  push:

jobs:
  cache-1:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: test
          key: test
  cache-2:
    needs: [cache-1]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: test
          key: test
        working-directory: test
      - run: ls -la test; ls -la test/test
