---
name: Test Cache

on:
  push:
    branches: [main]

defaults:
 run:
  working-directory: ./test

env:
  pr: 1

jobs:
  cache-1:
    if: ${{ env.pr }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: test
          key: foo-${{ github.run_id }}
      - run: mkdir run; touch run/foo; exit 1
  cache-2:
    needs: [cache-1]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: test
          key: bar-${{ github.run_id }}
      - run: mkdir run; touch run/bar
  cache-3:
    needs: [cache-1, cache-2]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: test
          key: foo-${{ github.run_id }}
      - run: mkdir before; rsync -av run/ before; rm -rf run
      - uses: actions/cache@v3
        with:
          path: test
          key: bar-${{ github.run_id }}
      - run: mkdir after; rsync -av run/ after; rm -rf run
      - run: ls -la **/**
